"""Add new student fields

Revision ID: 48f761fbe968
Revises: 3e18f816839a
Create Date: 2025-07-27 12:45:00.269165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48f761fbe968'
down_revision: Union[str, Sequence[str], None] = '3e18f816839a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('mother_name', sa.String(), nullable=True))
    op.add_column('students', sa.Column('roll_number', sa.String(), nullable=True))
    op.add_column('students', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('students', sa.Column('class_grade', sa.String(), nullable=True))
    op.add_column('students', sa.Column('parent_mobile', sa.String(), nullable=True))
    op.add_column('students', sa.Column('emergency_contact', sa.String(), nullable=True))
    op.drop_column('students', 'phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('students', 'emergency_contact')
    op.drop_column('students', 'parent_mobile')
    op.drop_column('students', 'class_grade')
    op.drop_column('students', 'gender')
    op.drop_column('students', 'roll_number')
    op.drop_column('students', 'mother_name')
    # ### end Alembic commands ###
